; Generated by ImageToGcode 1.2.9 (6/7/2020 9:37:23 AM)
; Contact: viktorglekler@gmail.com


; Parameters:
;
;    Min Power: 0 %
;    Max Power: 0 %
;    PWM Resolution: 255
;    Burn Speed: 0 mm/s
;    Travel Speed: 0 mm/s
;    Vertical Resolution: 0.1 mm
;    Horizontal Resolution: 0.1 mm
;
; Size:
;
;    Width: 135.47 mm
;    Height: 135.47 mm
;
; Origin location:
;
;    X 0 mm
;    Y 0 mm
;    Z 0 mm

G21 ; Set units to metric
G90 ; Absolute coordinates


